# Generated by Django 2.2.1 on 2019-09-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enviar_sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, default='--', max_length=18, null=True)),
                ('email', models.EmailField(blank=True, default='sms@gmail.com', max_length=60, null=True)),
                ('sms', models.CharField(blank=True, max_length=390, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=12)),
                ('data_nascimento', models.DateField()),
                ('bi', models.CharField(max_length=20, unique=True)),
                ('residencia', models.CharField(blank=True, max_length=90, null=True)),
                ('telefone', models.CharField(blank=True, default='--', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, default='sms@gmail.com', max_length=60, null=True)),
            ],
        ),
    ]
