# Generated by Django 2.2.1 on 2019-09-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviar_sms',
            name='email',
        ),
        migrations.AlterField(
            model_name='enviar_sms',
            name='telefone',
            field=models.CharField(default=' ', max_length=18),
        ),
    ]
